package logic_core.infrastructure.transport;

public enum ResponseType
{
    AUTH_REGISTER_RESPONSE,
    AUTH_LOGIN_RESPONSE,
    AUTH_LOGOUT_RESPONSE,
    AUTH_REFRESH_RESPONSE,
    UNKNOWN_REQUEST,
    BAD_REQUEST,
    AUTH_REQUEST_PASSWORD_RESET_RESPONSE,
    AUTH_VERIFY_PASSWORD_RESET_CODE_RESPONSE,
    AUTH_RESET_PASSWORD_RESPONSE,

    CONVERSATION_CREATE_RESPONSE,
    CONVERSATION_ADD_MEMBER_RESPONSE,
    CONVERSATION_REMOVE_MEMBER_RESPONSE,
    CONVERSATION_DELETE_RESPONSE,
    CONVERSATION_GET_RESPONSE,

    MESSAGE_SEND_RESPONSE,
    MESSAGE_EDIT_RESPONSE,
    MESSAGE_DELETE_RESPONSE,
    MESSAGE_GET_RESPONSE,
    MESSAGE_GET_CONVERSATION_RESPONSE,

    RELATION_FOLLOW_RESPONSE,
    RELATION_UNFOLLOW_RESPONSE,
    RELATION_BLOCK_RESPONSE,
    RELATION_UNBLOCK_RESPONSE,
    RELATION_MUTE_RESPONSE,
    RELATION_UNMUTE_RESPONSE,

    TIMELINE_GET_RESPONSE,

    TWEET_CREATE_RESPONSE,
    TWEET_DELETE_RESPONSE,
    TWEET_EDIT_RESPONSE,
    TWEET_LIKE_RESPONSE,
    TWEET_UNLIKE_RESPONSE,
    TWEET_REPLY_RESPONSE,
    TWEET_RETWEET_RESPONSE,
    TWEET_UNRETWEET_RESPONSE,
    TWEET_GET_RESPONSE,
    TWEET_GET_REPLY_RESPONSE,

    NOTIFICATION_GET_RESPONSE,
    NOTIFICATION_READ_RESPONSE,
    NOTIFICATION_READ_ALL_RESPONSE,

    USER_GET_PROFILE_RESPONSE,
    USER_SEARCH_RESPONSE,
    USER_UPDATE_PROFILE_RESPONSE,
    USER_UPDATE_BIO_RESPONSE,
    USER_UPDATE_AVATAR_RESPONSE,
    USER_UPDATE_BANNER_RESPONSE,
    USER_UPDATE_EMAIL_RESPONSE,
    USER_UPDATE_PASSWORD_RESPONSE,
    USER_DELETE_ACCOUNT_RESPONSE,
    USER_UPDATE_COMPLETE_PROFILE_RESPONSE,
    USER_GET_IS_FOLLOW_RESPONSE,
    USER_GET_IS_LIKE_RESPONSE,

    FOLLOW_GET_FOLLOWERS_RESPONSE,
    FOLLOW_GET_FOLLOWINGS_RESPONSE,

    MEDIA_DOWNLOAD_RESPONSE,
    MEDIA_DELETE_RESPONSE;


    public static ResponseType fromWire(String value)
    {
        if (value == null || value.isBlank())
        {
            return null;
        }

        try
        {
            return ResponseType.valueOf(value);
        }
        catch (IllegalArgumentException e)
        {
            return null;
        }
    }

    public String toWire()
    {
        return name();
    }
}
